import pytest
from config import Config

from app import create_app
from app import db

from app.models import Role
from app.models import User
from app.models import EmailOTP
from app.utils import OTPService


# ============================================================
# TEST CONFIGURATION
# ============================================================


class TestConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
    WTF_CSRF_ENABLED = False

@pytest.fixture
def app():
    """
    Create a Flask application for testing.
    """

    app = create_app(TestConfig)

    with app.app_context():

        db.create_all()

        # Create default User role
        user_role = Role(
            name="User",
            description="Normal application user"
        )

        db.session.add(user_role)
        db.session.commit()

        yield app

        db.session.remove()
        db.drop_all()


@pytest.fixture
def client(app):
    """
    Flask test client.
    """
    return app.test_client()


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_test_otp(user_id):
    """
    Get the latest unverified OTP for a user.
    """

    return (
        EmailOTP.query
        .filter_by(
            user_id=user_id,
            verified=False
        )
        .order_by(
            EmailOTP.created_at.desc()
        )
        .first()
    )


def get_plain_otp(monkeypatch):
    """
    Capture OTP generated by OTPService.

    This allows us to test OTP verification without
    depending on a real email server.
    """

    generated_otp = {
        "value": None
    }

    original_generate = OTPService.generate_otp

    def generate_otp():
        otp = original_generate()
        generated_otp["value"] = otp
        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    return generated_otp


# ============================================================
# 1. APPLICATION / DATABASE TEST
# ============================================================

def test_application_starts(app):

    assert app is not None

    with app.app_context():
        roles = Role.query.all()

        assert len(roles) == 1
        assert roles[0].name == "User"


# ============================================================
# 2. REGISTER USER
# ============================================================

def test_register_user(client, app, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    # Prevent real email from being sent
    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Talal",
            "last_name": "Zahid",
            "email": "test@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 201

    data = response.get_json()

    assert data["success"] is True

    with app.app_context():

        user = User.query.filter_by(
            email="test@example.com"
        ).first()

        assert user is not None

        assert user.first_name == "Talal"
        assert user.last_name == "Zahid"

        # Email should not be verified yet
        assert user.is_verified is False

        # User should be active
        assert user.is_active is True

        # Role must exist
        assert user.role_id is not None
        assert user.role.name == "User"

        # Password must be hashed
        assert user.password_hash != "Password@123"

        # OTP should exist
        otp = get_test_otp(user.id)

        assert otp is not None
        assert otp.otp_hash is not None
        assert otp.verified is False
        assert otp.expires_at is not None

        # Plain OTP must never be stored
        assert otp.otp_hash != captured_otp["value"]


# ============================================================
# 3. VERIFY OTP
# ============================================================

def test_verify_otp(client, app, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    register_response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Talal",
            "last_name": "Zahid",
            "email": "verify@example.com",
            "password": "Password@123"
        }
    )

    assert register_response.status_code == 201

    # Verify OTP
    response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "verify@example.com",
            "otp": captured_otp["value"]
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True

    with app.app_context():

        user = User.query.filter_by(
            email="verify@example.com"
        ).first()

        assert user.is_verified is True

        otp = (
            EmailOTP.query
            .filter_by(user_id=user.id)
            .order_by(EmailOTP.created_at.desc())
            .first()
        )

        assert otp.verified is True


# ============================================================
# 4. SAME OTP CANNOT BE USED AGAIN
# ============================================================

def test_same_otp_cannot_be_reused(
    client,
    app,
    monkeypatch
):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
    "app.utils.email_services.EmailService.send_otp",
    lambda email, otp: True)

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Talal",
            "last_name": "Zahid",
            "email": "reuse@example.com",
            "password": "Password@123"
        }
    )

    # First verification
    first_response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "reuse@example.com",
            "otp": captured_otp["value"]
        }
    )

    assert first_response.status_code == 200

    # Try same OTP again
    second_response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "reuse@example.com",
            "otp": captured_otp["value"]
        }
    )

    assert second_response.status_code == 400


# ============================================================
# 5. WRONG OTP
# ============================================================

def test_wrong_otp(client, monkeypatch):

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Wrong",
            "last_name": "OTP",
            "email": "wrongotp@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 201

    response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "wrongotp@example.com",
            "otp": "111111"
        }
    )

    assert response.status_code == 400

    data = response.get_json()

    assert data["success"] is False


# ============================================================
# 6. EXPIRED OTP
# ============================================================

def test_expired_otp(client, app, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Expired",
            "last_name": "OTP",
            "email": "expired@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 201

    # Change expiry to the past
    with app.app_context():

        user = User.query.filter_by(
            email="expired@example.com"
        ).first()

        otp = get_test_otp(user.id)

        from datetime import datetime, timedelta

        otp.expires_at = (
            datetime.utcnow() - timedelta(minutes=1)
        )

        db.session.commit()

    # Try expired OTP
    response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "expired@example.com",
            "otp": captured_otp["value"]
        }
    )

    assert response.status_code == 400

    data = response.get_json()

    assert data["success"] is False
    assert "expired" in data["message"].lower()


# ============================================================
# 7. RESEND OTP
# ============================================================

def test_resend_otp(client, app, monkeypatch):

    captured_otps = []

    original_generate = OTPService.generate_otp

    def generate_otp():

        otp = original_generate()

        captured_otps.append(otp)

        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Resend",
            "last_name": "Test",
            "email": "resend@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 201

    first_otp = captured_otps[-1]

    # Resend
    response = client.post(
        "/api/auth/resend-otp",
        json={
            "email": "resend@example.com"
        }
    )

    assert response.status_code == 200

    second_otp = captured_otps[-1]

    # A new OTP should be generated
    assert second_otp != first_otp

    with app.app_context():

        user = User.query.filter_by(
            email="resend@example.com"
        ).first()

        otps = (
            EmailOTP.query
            .filter_by(user_id=user.id)
            .order_by(EmailOTP.created_at.asc())
            .all()
        )

        assert len(otps) == 2


# ============================================================
# 8. LOGIN
# ============================================================

def test_login(client, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Login",
            "last_name": "User",
            "email": "login@example.com",
            "password": "Password@123"
        }
    )

    # Verify
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "login@example.com",
            "otp": captured_otp["value"]
        }
    )

    # Login
    response = client.post(
        "/api/auth/login",
        json={
            "email": "login@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True

    assert "access_token" in data["data"]
    assert "refresh_token" in data["data"]

    assert data["data"]["user"]["email"] == (
        "login@example.com"
    )


# ============================================================
# 9. WRONG PASSWORD
# ============================================================

def test_wrong_password(client, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Wrong",
            "last_name": "Password",
            "email": "wrongpassword@example.com",
            "password": "Password@123"
        }
    )

    # Verify
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "wrongpassword@example.com",
            "otp": captured_otp["value"]
        }
    )

    # Login using wrong password
    response = client.post(
        "/api/auth/login",
        json={
            "email": "wrongpassword@example.com",
            "password": "WrongPassword123"
        }
    )

    assert response.status_code == 401

    data = response.get_json()

    assert data["success"] is False
    assert data["message"] == "Invalid email or password."


# ============================================================
# 10. UNVERIFIED USER CANNOT LOGIN
# ============================================================

def test_unverified_user_cannot_login(
    client,
    monkeypatch
):

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register but DO NOT verify
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Unverified",
            "last_name": "User",
            "email": "unverified@example.com",
            "password": "Password@123"
        }
    )

    # Try login
    response = client.post(
        "/api/auth/login",
        json={
            "email": "unverified@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 403

    data = response.get_json()

    assert data["success"] is False
    assert "verify" in data["message"].lower()


# ============================================================
# 11. DUPLICATE REGISTERED EMAIL
# ============================================================

def test_duplicate_registered_email(
    client,
    monkeypatch
):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # First registration
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Duplicate",
            "last_name": "User",
            "email": "duplicate@example.com",
            "password": "Password@123"
        }
    )

    # Verify
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "duplicate@example.com",
            "otp": captured_otp["value"]
        }
    )

    # Try registering same email again
    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Another",
            "last_name": "User",
            "email": "duplicate@example.com",
            "password": "AnotherPassword@123"
        }
    )

    assert response.status_code == 409

    data = response.get_json()

    assert data["success"] is False


# ============================================================
# 12. FORGOT PASSWORD
# ============================================================

def test_forgot_password(
    client,
    app,
    monkeypatch
):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_password_reset_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Forgot",
            "last_name": "Password",
            "email": "forgot@example.com",
            "password": "Password@123"
        }
    )

    # Verify account
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "forgot@example.com",
            "otp": captured_otp["value"]
        }
    )

    # Request password reset
    response = client.post(
        "/api/auth/forgot-password",
        json={
            "email": "forgot@example.com"
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True

    with app.app_context():

        user = User.query.filter_by(
            email="forgot@example.com"
        ).first()

        otp = get_test_otp(user.id)

        assert otp is not None
        assert otp.verified is False


# ============================================================
# 13. RESET PASSWORD
# ============================================================

def test_reset_password(
    client,
    monkeypatch
):

    captured_otps = []

    original_generate = OTPService.generate_otp

    def generate_otp():

        otp = original_generate()

        captured_otps.append(otp)

        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_password_reset_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Reset",
            "last_name": "Password",
            "email": "reset@example.com",
            "password": "OldPassword@123"
        }
    )

    registration_otp = captured_otps[-1]

    # Verify account
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "reset@example.com",
            "otp": registration_otp
        }
    )

    # Request reset OTP
    client.post(
        "/api/auth/forgot-password",
        json={
            "email": "reset@example.com"
        }
    )

    reset_otp = captured_otps[-1]

    # Reset password
    response = client.post(
        "/api/auth/reset-password",
        json={
            "email": "reset@example.com",
            "otp": reset_otp,
            "new_password": "NewPassword@123"
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True


# ============================================================
# 14. OLD PASSWORD SHOULD NOT WORK
# ============================================================

def test_old_password_after_reset(
    client,
    monkeypatch
):

    captured_otps = []

    original_generate = OTPService.generate_otp

    def generate_otp():

        otp = original_generate()

        captured_otps.append(otp)

        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_password_reset_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Password",
            "last_name": "Change",
            "email": "change@example.com",
            "password": "OldPassword@123"
        }
    )

    # Verify
    registration_otp = captured_otps[-1]

    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "change@example.com",
            "otp": registration_otp
        }
    )

    # Forgot password
    client.post(
        "/api/auth/forgot-password",
        json={
            "email": "change@example.com"
        }
    )

    reset_otp = captured_otps[-1]

    # Reset
    client.post(
        "/api/auth/reset-password",
        json={
            "email": "change@example.com",
            "otp": reset_otp,
            "new_password": "NewPassword@123"
        }
    )

    # Try old password
    response = client.post(
        "/api/auth/login",
        json={
            "email": "change@example.com",
            "password": "OldPassword@123"
        }
    )

    assert response.status_code == 401


# ============================================================
# 15. NEW PASSWORD SHOULD WORK
# ============================================================

def test_new_password_after_reset(
    client,
    monkeypatch
):

    captured_otps = []

    original_generate = OTPService.generate_otp

    def generate_otp():

        otp = original_generate()

        captured_otps.append(otp)

        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_password_reset_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "New",
            "last_name": "Password",
            "email": "newpassword@example.com",
            "password": "OldPassword@123"
        }
    )

    # Verify
    registration_otp = captured_otps[-1]

    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "newpassword@example.com",
            "otp": registration_otp
        }
    )

    # Forgot password
    client.post(
        "/api/auth/forgot-password",
        json={
            "email": "newpassword@example.com"
        }
    )

    reset_otp = captured_otps[-1]

    # Reset password
    client.post(
        "/api/auth/reset-password",
        json={
            "email": "newpassword@example.com",
            "otp": reset_otp,
            "new_password": "NewPassword@123"
        }
    )

    # Login with new password
    response = client.post(
        "/api/auth/login",
        json={
            "email": "newpassword@example.com",
            "password": "NewPassword@123"
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True

    assert "access_token" in data["data"]
    assert "refresh_token" in data["data"]

