import pytest
from config import Config

from flask_jwt_extended import create_access_token

from app import create_app
from app import db

from app.models import Role
from app.models import User
from app.models import EmailOTP, Notification, ContactMessage
from app.notifications.service import create_notification, notify_all_admins
from app.utils import OTPService


# ============================================================
# TEST CONFIGURATION
# ============================================================


class TestConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
    WTF_CSRF_ENABLED = False

@pytest.fixture
def app():
    """
    Create a Flask application for testing.
    """

    app = create_app(TestConfig)

    with app.app_context():

        db.create_all()

        # Create default User role
        user_role = Role(
            name="User",
            description="Normal application user"
        )

        db.session.add(user_role)
        db.session.commit()

        yield app

        db.session.remove()
        db.drop_all()


@pytest.fixture
def client(app):
    """
    Flask test client.
    """
    return app.test_client()


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_test_otp(user_id):
    """
    Get the latest unverified OTP for a user.
    """

    return (
        EmailOTP.query
        .filter_by(
            user_id=user_id,
            verified=False
        )
        .order_by(
            EmailOTP.created_at.desc()
        )
        .first()
    )


def get_plain_otp(monkeypatch):
    """
    Capture OTP generated by OTPService.

    This allows us to test OTP verification without
    depending on a real email server.
    """

    generated_otp = {
        "value": None
    }

    original_generate = OTPService.generate_otp

    def generate_otp():
        otp = original_generate()
        generated_otp["value"] = otp
        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    return generated_otp


# ============================================================
# 1. APPLICATION / DATABASE TEST
# ============================================================

def test_application_starts(app):

    assert app is not None

    with app.app_context():
        roles = Role.query.all()

        assert len(roles) == 1
        assert roles[0].name == "User"


# ============================================================
# 2. REGISTER USER
# ============================================================

def test_register_user(client, app, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    # Prevent real email from being sent
    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Talal",
            "last_name": "Zahid",
            "email": "test@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 201

    data = response.get_json()

    assert data["success"] is True

    with app.app_context():

        user = User.query.filter_by(
            email="test@example.com"
        ).first()

        assert user is not None

        assert user.first_name == "Talal"
        assert user.last_name == "Zahid"

        # Email should not be verified yet
        assert user.is_verified is False

        # User should be active
        assert user.is_active is True

        # Role must exist
        assert user.role_id is not None
        assert user.role.name == "User"

        # Password must be hashed
        assert user.password_hash != "Password@123"

        # OTP should exist
        otp = get_test_otp(user.id)

        assert otp is not None
        assert otp.otp_hash is not None
        assert otp.verified is False
        assert otp.expires_at is not None

        # Plain OTP must never be stored
        assert otp.otp_hash != captured_otp["value"]


def test_notification_helpers_create_records(app):
    with app.app_context():
        role = Role.query.filter_by(name="User").first()
        user = User(
            first_name="Ayesha",
            last_name="Khan",
            email="notify@example.com",
            password_hash="hash",
            role_id=role.id,
            is_verified=True,
        )
        db.session.add(user)
        db.session.commit()

        create_notification(
            user.id,
            "Welcome",
            "Your account is ready.",
            notification_type="welcome",
            redirect_url="/dashboard",
        )

        admin_role = Role(name="Admin", description="Store administrator")
        db.session.add(admin_role)
        db.session.commit()

        admin = User(
            first_name="Admin",
            last_name="User",
            email="adminnotify@example.com",
            password_hash="hash",
            role_id=admin_role.id,
            is_verified=True,
        )
        db.session.add(admin)
        db.session.commit()

        notify_all_admins(
            "New sign-up",
            "A new user joined.",
            notification_type="registration",
            related_id=user.id,
            redirect_url="/admin/users",
        )

        assert Notification.query.filter_by(user_id=user.id).count() == 1
        assert Notification.query.filter_by(user_id=admin.id).count() == 1


def test_notifications_api_returns_user_notifications(client, app):
    with app.app_context():
        role = Role.query.filter_by(name="User").first()
        user = User(
            first_name="Api",
            last_name="User",
            email="api_notify@example.com",
            password_hash="hash",
            role_id=role.id,
            is_verified=True,
        )
        db.session.add(user)
        db.session.commit()
        create_notification(
            user.id,
            "API check",
            "Notification returned through API",
            notification_type="api_test",
            redirect_url="/dashboard",
        )
        token = create_access_token(identity=str(user.id))

        response = client.get('/api/notifications', headers={'Authorization': f'Bearer {token}'})

        assert response.status_code == 200
        payload = response.get_json()
        assert payload['success'] is True
        assert any(item['title'] == 'API check' for item in payload['data'])


def test_admin_contact_messages_list_and_reply(client, app):
    with app.app_context():
        user_role = Role.query.filter_by(name="User").first()
        admin_role = Role.query.filter_by(name="Admin").first()
        if not admin_role:
            admin_role = Role(name="Admin", description="Store administrator")
            db.session.add(admin_role)
            db.session.commit()

        user = User(
            first_name="Customer",
            last_name="One",
            email="customer@example.com",
            password_hash="hash",
            role_id=user_role.id,
            is_verified=True,
        )
        admin = User(
            first_name="Admin",
            last_name="User",
            email="admin@example.com",
            password_hash="hash",
            role_id=admin_role.id,
            is_verified=True,
            is_active=True,
        )
        db.session.add_all([user, admin])
        db.session.commit()

        message = ContactMessage(
            user_id=user.id,
            name="Customer One",
            email=user.email,
            subject="Support request",
            message="I need help with my order.",
            status="new",
        )
        db.session.add(message)
        db.session.commit()

        token = create_access_token(identity=str(admin.id))

        list_response = client.get('/api/admin/contact-messages', headers={'Authorization': f'Bearer {token}'})
        assert list_response.status_code == 200
        list_payload = list_response.get_json()
        assert list_payload['success'] is True
        assert any(item['id'] == message.id for item in list_payload['data'])

        reply_response = client.post(
            f'/api/admin/contact-messages/{message.id}/reply',
            json={'reply': 'Thanks for reaching out.'},
            headers={'Authorization': f'Bearer {token}'},
        )
        assert reply_response.status_code == 200
        reply_payload = reply_response.get_json()
        assert reply_payload['success'] is True
        assert reply_payload['data']['is_replied'] is True

        updated_message = ContactMessage.query.get(message.id)
        assert updated_message.reply == 'Thanks for reaching out.'
        assert updated_message.is_replied is True
        assert Notification.query.filter_by(user_id=user.id, notification_type='contact_reply').count() == 1


def test_admin_contact_reply_registered_user_uses_email_and_notification(client, app, monkeypatch):
    with app.app_context():
        user_role = Role.query.filter_by(name="User").first()
        admin_role = Role.query.filter_by(name="Admin").first()
        if not admin_role:
            admin_role = Role(name="Admin", description="Store administrator")
            db.session.add(admin_role)
            db.session.commit()

        user = User(
            first_name="Guest",
            last_name="User",
            email="reply.user@example.com",
            password_hash="hash",
            role_id=user_role.id,
            is_verified=True,
        )
        admin = User(
            first_name="Admin",
            last_name="User",
            email="admin@example.com",
            password_hash="hash",
            role_id=admin_role.id,
            is_verified=True,
            is_active=True,
        )
        db.session.add_all([user, admin])
        db.session.commit()

        message = ContactMessage(
            user_id=None,
            name="Guest User",
            email="reply.user@example.com",
            subject="Order status",
            message="Where is my order?",
            status="new",
        )
        db.session.add(message)
        db.session.commit()

        captured = {}

        def fake_send(email, subject, original_message, admin_reply):
            captured['email'] = email
            captured['subject'] = subject
            captured['original_message'] = original_message
            captured['admin_reply'] = admin_reply
            return True

        monkeypatch.setattr('app.utils.email_services.EmailService.send_contact_reply', fake_send)

        token = create_access_token(identity=str(admin.id))
        response = client.post(
            f'/api/admin/contact-messages/{message.id}/reply',
            json={'reply': 'Your order is on the way.'},
            headers={'Authorization': f'Bearer {token}'},
        )

        assert response.status_code == 200
        payload = response.get_json()
        assert payload['success'] is True
        assert payload['email_sent'] is True
        assert payload['delivery_method'] == 'email_and_notification'
        assert payload['recipient_is_registered_user'] is True
        assert captured['email'] == 'reply.user@example.com'
        assert Notification.query.filter_by(user_id=user.id, notification_type='contact_reply').count() == 1


def test_admin_contact_reply_guest_user_sends_email_only(client, app, monkeypatch):
    with app.app_context():
        admin_role = Role.query.filter_by(name="Admin").first()
        if not admin_role:
            admin_role = Role(name="Admin", description="Store administrator")
            db.session.add(admin_role)
            db.session.commit()

        admin = User(
            first_name="Admin",
            last_name="User",
            email="admin@example.com",
            password_hash="hash",
            role_id=admin_role.id,
            is_verified=True,
            is_active=True,
        )
        db.session.add(admin)
        db.session.commit()

        message = ContactMessage(
            user_id=None,
            name="Guest Visitor",
            email="guest@example.com",
            subject="General inquiry",
            message="I want to ask something.",
            status="new",
        )
        db.session.add(message)
        db.session.commit()

        captured = {}

        def fake_send(email, subject, original_message, admin_reply):
            captured['email'] = email
            captured['subject'] = subject
            captured['original_message'] = original_message
            captured['admin_reply'] = admin_reply
            return True

        monkeypatch.setattr('app.utils.email_services.EmailService.send_contact_reply', fake_send)

        token = create_access_token(identity=str(admin.id))
        response = client.post(
            f'/api/admin/contact-messages/{message.id}/reply',
            json={'reply': 'Thanks for your message.'},
            headers={'Authorization': f'Bearer {token}'},
        )

        assert response.status_code == 200
        payload = response.get_json()
        assert payload['success'] is True
        assert payload['email_sent'] is True
        assert payload['delivery_method'] == 'email_only'
        assert payload['recipient_is_registered_user'] is False
        assert captured['email'] == 'guest@example.com'
        assert Notification.query.filter_by(notification_type='contact_reply').count() == 0


# ============================================================
# 3. VERIFY OTP
# ============================================================

def test_verify_otp(client, app, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    register_response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Talal",
            "last_name": "Zahid",
            "email": "verify@example.com",
            "password": "Password@123"
        }
    )

    assert register_response.status_code == 201

    # Verify OTP
    response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "verify@example.com",
            "otp": captured_otp["value"]
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True

    with app.app_context():

        user = User.query.filter_by(
            email="verify@example.com"
        ).first()

        assert user.is_verified is True

        otp = (
            EmailOTP.query
            .filter_by(user_id=user.id)
            .order_by(EmailOTP.created_at.desc())
            .first()
        )

        assert otp.verified is True


# ============================================================
# 4. SAME OTP CANNOT BE USED AGAIN
# ============================================================

def test_same_otp_cannot_be_reused(
    client,
    app,
    monkeypatch
):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
    "app.utils.email_services.EmailService.send_otp",
    lambda email, otp: True)

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Talal",
            "last_name": "Zahid",
            "email": "reuse@example.com",
            "password": "Password@123"
        }
    )

    # First verification
    first_response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "reuse@example.com",
            "otp": captured_otp["value"]
        }
    )

    assert first_response.status_code == 200

    # Try same OTP again
    second_response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "reuse@example.com",
            "otp": captured_otp["value"]
        }
    )

    assert second_response.status_code == 400


# ============================================================
# 5. WRONG OTP
# ============================================================

def test_wrong_otp(client, monkeypatch):

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Wrong",
            "last_name": "OTP",
            "email": "wrongotp@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 201

    response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "wrongotp@example.com",
            "otp": "111111"
        }
    )

    assert response.status_code == 400

    data = response.get_json()

    assert data["success"] is False


# ============================================================
# 6. EXPIRED OTP
# ============================================================

def test_expired_otp(client, app, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Expired",
            "last_name": "OTP",
            "email": "expired@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 201

    # Change expiry to the past
    with app.app_context():

        user = User.query.filter_by(
            email="expired@example.com"
        ).first()

        otp = get_test_otp(user.id)

        from datetime import datetime, timedelta

        otp.expires_at = (
            datetime.utcnow() - timedelta(minutes=1)
        )

        db.session.commit()

    # Try expired OTP
    response = client.post(
        "/api/auth/verify-otp",
        json={
            "email": "expired@example.com",
            "otp": captured_otp["value"]
        }
    )

    assert response.status_code == 400

    data = response.get_json()

    assert data["success"] is False
    assert "expired" in data["message"].lower()


# ============================================================
# 7. RESEND OTP
# ============================================================

def test_resend_otp(client, app, monkeypatch):

    captured_otps = []

    original_generate = OTPService.generate_otp

    def generate_otp():

        otp = original_generate()

        captured_otps.append(otp)

        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Resend",
            "last_name": "Test",
            "email": "resend@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 201

    first_otp = captured_otps[-1]

    # Resend
    response = client.post(
        "/api/auth/resend-otp",
        json={
            "email": "resend@example.com"
        }
    )

    assert response.status_code == 200

    second_otp = captured_otps[-1]

    # A new OTP should be generated
    assert second_otp != first_otp

    with app.app_context():

        user = User.query.filter_by(
            email="resend@example.com"
        ).first()

        otps = (
            EmailOTP.query
            .filter_by(user_id=user.id)
            .order_by(EmailOTP.created_at.asc())
            .all()
        )

        assert len(otps) == 2


# ============================================================
# 8. LOGIN
# ============================================================

def test_login(client, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Login",
            "last_name": "User",
            "email": "login@example.com",
            "password": "Password@123"
        }
    )

    # Verify
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "login@example.com",
            "otp": captured_otp["value"]
        }
    )

    # Login
    response = client.post(
        "/api/auth/login",
        json={
            "email": "login@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True

    assert "access_token" in data["data"]
    assert "refresh_token" in data["data"]

    assert data["data"]["user"]["email"] == (
        "login@example.com"
    )


# ============================================================
# 9. WRONG PASSWORD
# ============================================================

def test_wrong_password(client, monkeypatch):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Wrong",
            "last_name": "Password",
            "email": "wrongpassword@example.com",
            "password": "Password@123"
        }
    )

    # Verify
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "wrongpassword@example.com",
            "otp": captured_otp["value"]
        }
    )

    # Login using wrong password
    response = client.post(
        "/api/auth/login",
        json={
            "email": "wrongpassword@example.com",
            "password": "WrongPassword123"
        }
    )

    assert response.status_code == 401

    data = response.get_json()

    assert data["success"] is False
    assert data["message"] == "Invalid email or password."


# ============================================================
# 10. UNVERIFIED USER CANNOT LOGIN
# ============================================================

def test_unverified_user_cannot_login(
    client,
    monkeypatch
):

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # Register but DO NOT verify
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Unverified",
            "last_name": "User",
            "email": "unverified@example.com",
            "password": "Password@123"
        }
    )

    # Try login
    response = client.post(
        "/api/auth/login",
        json={
            "email": "unverified@example.com",
            "password": "Password@123"
        }
    )

    assert response.status_code == 403

    data = response.get_json()

    assert data["success"] is False
    assert "verify" in data["message"].lower()


# ============================================================
# 11. DUPLICATE REGISTERED EMAIL
# ============================================================

def test_duplicate_registered_email(
    client,
    monkeypatch
):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    # First registration
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Duplicate",
            "last_name": "User",
            "email": "duplicate@example.com",
            "password": "Password@123"
        }
    )

    # Verify
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "duplicate@example.com",
            "otp": captured_otp["value"]
        }
    )

    # Try registering same email again
    response = client.post(
        "/api/auth/register",
        json={
            "first_name": "Another",
            "last_name": "User",
            "email": "duplicate@example.com",
            "password": "AnotherPassword@123"
        }
    )

    assert response.status_code == 409

    data = response.get_json()

    assert data["success"] is False


# ============================================================
# 12. FORGOT PASSWORD
# ============================================================

def test_forgot_password(
    client,
    app,
    monkeypatch
):

    captured_otp = get_plain_otp(monkeypatch)

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_password_reset_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Forgot",
            "last_name": "Password",
            "email": "forgot@example.com",
            "password": "Password@123"
        }
    )

    # Verify account
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "forgot@example.com",
            "otp": captured_otp["value"]
        }
    )

    # Request password reset
    response = client.post(
        "/api/auth/forgot-password",
        json={
            "email": "forgot@example.com"
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True

    with app.app_context():

        user = User.query.filter_by(
            email="forgot@example.com"
        ).first()

        otp = get_test_otp(user.id)

        assert otp is not None
        assert otp.verified is False


# ============================================================
# 13. RESET PASSWORD
# ============================================================

def test_reset_password(
    client,
    monkeypatch
):

    captured_otps = []

    original_generate = OTPService.generate_otp

    def generate_otp():

        otp = original_generate()

        captured_otps.append(otp)

        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_password_reset_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Reset",
            "last_name": "Password",
            "email": "reset@example.com",
            "password": "OldPassword@123"
        }
    )

    registration_otp = captured_otps[-1]

    # Verify account
    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "reset@example.com",
            "otp": registration_otp
        }
    )

    # Request reset OTP
    client.post(
        "/api/auth/forgot-password",
        json={
            "email": "reset@example.com"
        }
    )

    reset_otp = captured_otps[-1]

    # Reset password
    response = client.post(
        "/api/auth/reset-password",
        json={
            "email": "reset@example.com",
            "otp": reset_otp,
            "new_password": "NewPassword@123"
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True


# ============================================================
# 14. OLD PASSWORD SHOULD NOT WORK
# ============================================================

def test_old_password_after_reset(
    client,
    monkeypatch
):

    captured_otps = []

    original_generate = OTPService.generate_otp

    def generate_otp():

        otp = original_generate()

        captured_otps.append(otp)

        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_password_reset_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Password",
            "last_name": "Change",
            "email": "change@example.com",
            "password": "OldPassword@123"
        }
    )

    # Verify
    registration_otp = captured_otps[-1]

    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "change@example.com",
            "otp": registration_otp
        }
    )

    # Forgot password
    client.post(
        "/api/auth/forgot-password",
        json={
            "email": "change@example.com"
        }
    )

    reset_otp = captured_otps[-1]

    # Reset
    client.post(
        "/api/auth/reset-password",
        json={
            "email": "change@example.com",
            "otp": reset_otp,
            "new_password": "NewPassword@123"
        }
    )

    # Try old password
    response = client.post(
        "/api/auth/login",
        json={
            "email": "change@example.com",
            "password": "OldPassword@123"
        }
    )

    assert response.status_code == 401


# ============================================================
# 15. NEW PASSWORD SHOULD WORK
# ============================================================

def test_new_password_after_reset(
    client,
    monkeypatch
):

    captured_otps = []

    original_generate = OTPService.generate_otp

    def generate_otp():

        otp = original_generate()

        captured_otps.append(otp)

        return otp

    monkeypatch.setattr(
        OTPService,
        "generate_otp",
        generate_otp
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_otp",
        lambda email, otp: True
    )

    monkeypatch.setattr(
        "app.utils.email_services.EmailService.send_password_reset_otp",
        lambda email, otp: True
    )

    # Register
    client.post(
        "/api/auth/register",
        json={
            "first_name": "New",
            "last_name": "Password",
            "email": "newpassword@example.com",
            "password": "OldPassword@123"
        }
    )

    # Verify
    registration_otp = captured_otps[-1]

    client.post(
        "/api/auth/verify-otp",
        json={
            "email": "newpassword@example.com",
            "otp": registration_otp
        }
    )

    # Forgot password
    client.post(
        "/api/auth/forgot-password",
        json={
            "email": "newpassword@example.com"
        }
    )

    reset_otp = captured_otps[-1]

    # Reset password
    client.post(
        "/api/auth/reset-password",
        json={
            "email": "newpassword@example.com",
            "otp": reset_otp,
            "new_password": "NewPassword@123"
        }
    )

    # Login with new password
    response = client.post(
        "/api/auth/login",
        json={
            "email": "newpassword@example.com",
            "password": "NewPassword@123"
        }
    )

    assert response.status_code == 200

    data = response.get_json()

    assert data["success"] is True

    assert "access_token" in data["data"]
    assert "refresh_token" in data["data"]

