"""add subcategory support to collections and occasions

Revision ID: 0918c950f364
Revises: 5429ba3b4467
Create Date: 2026-08-20 22:19:55.007531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0918c950f364'
down_revision = '5429ba3b4467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_collections_parent_id_collections', 'collections', ['parent_id'], ['id'])

    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_occasions_parent_id_occasions', 'occasions', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_occasions_parent_id_occasions', type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collections_parent_id_collections', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
