"""make card category_id optional

Revision ID: 470161b22be6
Revises: 0918c950f364
Create Date: 2026-08-21 16:41:33.052884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470161b22be6'
down_revision = '0918c950f364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
