"""add customization textbox

Revision ID: 8ff4011dfb70
Revises: afe9e7edd502
Create Date: 2026-09-15 01:19:50.398711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff4011dfb70'
down_revision = 'afe9e7edd502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customization_text_boxes',
    sa.Column('customization_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('font_color', sa.String(length=20), nullable=True),
    sa.Column('bold', sa.Boolean(), nullable=True),
    sa.Column('italic', sa.Boolean(), nullable=True),
    sa.Column('underline', sa.Boolean(), nullable=True),
    sa.Column('alignment', sa.String(length=20), nullable=True),
    sa.Column('letter_spacing', sa.Float(), nullable=True),
    sa.Column('line_height', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('z_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customization_id'], ['card_customizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customization_text_boxes')
    # ### end Alembic commands ###
