"""Add is default and positions in CardCustomization table

Revision ID: 911069844d71
Revises: 470161b22be6
Create Date: 2026-08-24 14:10:14.219179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911069844d71'
down_revision = '470161b22be6'
branch_labels = None
depends_on = None

def upgrade():
    # 1. Alter the table structure and safely add columns with defaults
    with op.batch_alter_table('card_customizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('position_x', sa.Float(), nullable=False, server_default=sa.text('0.0')))
        batch_op.add_column(sa.Column('position_y', sa.Float(), nullable=False, server_default=sa.text('0.0')))

    # 2. Create the dialect-specific partial index OUTSIDE of the batch block
    op.create_index(
        'uq_card_customizations_default_card', 
        'card_customizations', 
        ['card_id'], 
        unique=True, 
        sqlite_where=sa.text('is_default = 1'), 
        postgresql_where=sa.text('is_default = true')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_customizations', schema=None) as batch_op:
        batch_op.drop_index('uq_card_customizations_default_card', sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = true'))
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
