"""add featured_card_id to categories, collections, occasions

Revision ID: c4a7e91b2d3f
Revises: 8ff4011dfb70
Create Date: 2026-10-03 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a7e91b2d3f'
down_revision = '8ff4011dfb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_categories_featured_card_id_cards', 'cards', ['featured_card_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_collections_featured_card_id_cards', 'cards', ['featured_card_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_occasions_featured_card_id_cards', 'cards', ['featured_card_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occasions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_occasions_featured_card_id_cards', type_='foreignkey')
        batch_op.drop_column('featured_card_id')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collections_featured_card_id_cards', type_='foreignkey')
        batch_op.drop_column('featured_card_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_featured_card_id_cards', type_='foreignkey')
        batch_op.drop_column('featured_card_id')
    # ### end Alembic commands ###
