"""add parent_id to categories for subcategories

Revision ID: f2668bc0d29c
Revises: 9e5d12c26ffe
Create Date: 2026-08-16 23:33:40.870094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2668bc0d29c'
down_revision = '9e5d12c26ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_categories_parent_id_categories', 'categories', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_parent_id_categories', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
