"""add animated_gif to cards

Revision ID: fa58eef10e66
Revises: 9091cadd19b5
Create Date: 2026-08-30 10:41:59.297930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa58eef10e66'
down_revision = '9091cadd19b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animated_gif', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('animated_gif')

    # ### end Alembic commands ###
